language: java
before_install:
- cd ${TRAVIS_BUILD_DIR}/..
- git clone --depth=50 --branch=master https://github.com/vlingo/vlingo-common.git
- cd vlingo-common && mvn install -DskipTests=true
- cd ${TRAVIS_BUILD_DIR}/..
- git clone --depth=50 --branch=master https://github.com/vlingo/vlingo-actors.git
- cd vlingo-actors && mvn install -DskipTests=true
- cd ${TRAVIS_BUILD_DIR}/..
- git clone --depth=50 --branch=master https://github.com/vlingo/vlingo-symbio.git
- cd vlingo-symbio && mvn install -DskipTests=true
- cd ${TRAVIS_BUILD_DIR}
services:
- postgresql
addons:
  postgresql: '9.6'
before_script:
- psql -c "CREATE DATABASE vlingo_test;" -U postgres
- psql -c "CREATE USER vlingo_test WITH PASSWORD 'vlingo123' LOGIN NOSUPERUSER INHERIT
  CREATEDB NOCREATEROLE NOREPLICATION;" -U postgres
script:
- mvn install
deploy:
  provider: bintray
  file: bintray.json
  skip_cleanup: true
  user: vaughnvernon
  on:
    branch: master
  passphrase:
    secure: DWcRNjvNOjEB3iTIEmCIipVSPX12SXUiUgHzF4CtH7ZxyQzzsJzUsVweycrPcOe65SLZXZT4pkCMZiqd7joad3sG/J3s8SK8RAnuqqcPCn0or3yQrXqWJI6ux8QRV6vVb9DsRJNWQfu+PbsFCoQ1FqEaa60psjBwMeC2lbWU5ZwLxyuumuCDGlTrCJQHPZ6kVSevf/lCU2MO2KHSS76zTSKgPrE9p93Wfq4UswZWy+WRzBqYKosiu9pM0N1YExQxkLPZm128X8a+2C/nhCXSkEN9c2IOHim7w73eihAiQC63B4xKFpsyoZaPURdeEArDS0n5FvFOAlOF1wvIujqwBwsD+3AOMTNhM19iuSZ8S91LVewXEfbCj1VCXknnq3kYSm7w6IUdEfjDX4wYBwaIlyIv8tBHU9qD04u4aUFqA+BpykhfYXXtLW+scWedjbA4ALbK79sz1BIG/pBFP6Vch6dMAA2MF2z2Qtyq/hEZhItuDi+rl9iiwvUfbDRHnBvbPr7+qygNvaGIl/hflaQLejckdJ7nw8TJf5IXmJpZMsjtKYW29t66W2Bipbllc0HqzMwfG1+WAkIItNJKRSHkbbL7ggkgED9py8sLKs+ITFMUKBghfeOEv420v31r5x7MjN3hK+mokxz0IDmWseXKeZ+6EYEDefmia17hEkCJiiM=
  key:
    secure: dRfM1y/1CBCFT8QqUqkgAq0dNtMj0KZCgt3Ew4RXufGsGMzQcTXmQtIh1JAEsYApc1n6c8qMkzwVjD1uJjsY3Y/TP4ThlTRvD3w2Tc3ECynmKkH3BlMzezjJ37tHdf6EaSlSF58gG1iEwrZsYs64ig2K/wbfoMANMXFkPa//FXabDwCrpUcZTAa25ghQrCUMdNoTzbYIZoKAku3MwWDNJl4F/RfdYat0uVIlOvirew34ZIE00n1bFaf2UkYpmOGjbNE9C6u6ayBuhX0hBOGnigeS/gvKlCh444PwmCzeANVJAE3ifxxDHU80XtSbp3uiobiKUaqQy26Ed/x54zXkU/mCNj8G7MJHL1OgOYnLzgOgxn6b7r/CxH8llGM/786I74d/qZtLn2Avdf+cUJYXhF2YnrgVblBIZbxsahub5ADBba+nC7ZBFAfZ3RJr9Vo1GSedknhIoZ/ZZ83N7M3t3BMQKvS7RKBmcgWWUcZ7f2HfSs2v/r1LQekBVP1JegpvIOEUUGRcAkr5af3LQemaPdRW2XQr8ZUY2IyfYMBhjL6HcqZMKIar4X0ctwQl9dUP5kBSNjydq92CGhxIGiw1lQLEfNtG9SXMh6aJfeZEwItFhravIe1pADXbKA1M0QYDj8hkjvgNzMUfiMuZeyKpCu4/B2gGQFHfH9ImonkauQ0=
